spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cep_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        # Se você quiser usar um schema específico, descomente a linha abaixo:
        # default_schema: seu_schema_aqui

external:
  api:
    viacep:
      url: http://localhost:8081
